//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedwayBetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBets
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public int MatchID { get; set; }
        public string Bet { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual tblMatches tblMatches { get; set; }
        public virtual tblUsers tblUsers { get; set; }
    }
}
