//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpeedwayBetting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblMatches
    {
        public tblMatches()
        {
            this.tblBets = new HashSet<tblBets>();
        }
    
        public int ID { get; set; }
        public string Hosts { get; set; }
        public string Visitors { get; set; }
        public string Result { get; set; }
    
        public virtual ICollection<tblBets> tblBets { get; set; }
    }
}
